# Generated by Django 5.2.8 on 2025-11-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassRecord',
            new_name='GroupRecord',
        ),
        migrations.AddField(
            model_name='schedule',
            name='recurrence_days',
            field=models.CharField(blank=True, help_text='0=Monday, 6=Sunday', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='repeat_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
