# Generated by Django 5.2.8 on 2025-11-30 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_rename_classrecord_grouprecord_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouprecord',
            name='schedule',
        ),
        migrations.AddField(
            model_name='grouprecord',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scheduling.group'),
            preserve_default=False,
        ),
    ]
